services:
  - type: web
    name: legal-contract-analyzer
    env: python
    buildCommand: pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GROQ_API_KEY
        sync: false
      - key: HF_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: SECRET_KEY
        sync: false
